baseURL = "https://dustinnewman.net"
languageCode = "en-us"
title = "Dustin Newman"
enableInlineShortcodes = true
pygmentsCodeFences = false
pygmentsUseClasses = false

[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['$$', '$$']]
  inline = [['$', '$']]

[params]
  description = "Dustin Newman's blog"
  dark = "auto"
  highlight = false
  math = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 20

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]